on:
  push:
    branches:
      - main
jobs:
  Build_Deploy:
    runs-on: ubuntu-latest
    steps:
      # Init
      - uses: actions/checkout@v2

      # Variable declaration
      - id: S3BucketName
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "${{ github.workspace }}/parameters.json"
          prop_path: "S3BucketName"
      - id: StackName
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "${{ github.workspace }}/parameters.json"
          prop_path: "StackName"
      - id: Region
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "${{ github.workspace }}/parameters.json"
          prop_path: "Region"
      - id: CognitoAuthDomain
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "${{ github.workspace }}/parameters.json"
          prop_path: "CognitoUserPoolDomain"

      # AWS Config
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{steps.Region.outputs.prop}}

      # SAM Build
      - run: sam build --use-container

      # SAM Deploy
      - run: sam deploy --stack-name ${{steps.StackName.outputs.prop}} --region ${{steps.Region.outputs.prop}} --parameter-overrides CognitoUserPoolDomain=${{steps.CognitoAuthDomain.outputs.prop}} S3BucketName=${{steps.S3BucketName.outputs.prop}}  --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --resolve-s3

      # Describe CF and get output
      - run: npm install -C scripts/
      - run: node scripts/updateInfo.js ${{ github.workspace }} ${{steps.Region.outputs.prop}}

      # Build and Sync S#
      - run: yarn --cwd ${{ github.workspace }}/s3-website install
      - run: yarn --cwd ${{ github.workspace }}/s3-website build
      - run: aws s3 sync ${{ github.workspace }}/s3-website/build s3://${{steps.S3BucketName.outputs.prop}}
